import LinkedInIcon from '@mui/icons-material/LinkedIn';
import YouTubeIcon from '@mui/icons-material/YouTube';
import FacebookIcon from '@mui/icons-material/Facebook';
import PersonOutlineIcon from '@mui/icons-material/PersonOutline';
import Link from 'next/link';
import Navbar from './menu/navbar';

interface HeaderProps {
    title: string;
}

function Header({title}: HeaderProps) {

    return (
        <div>
            <Navbar /> 
            {/* <div className="flex text-white bg-blue-800 pr-16 pt-4" style={{height: '80px'}}> 
                <Link href="/">
                    <a><img src='/images/logo_sixtema_neg.png' height={30} className="pb-4"/></a>
                </Link>
                <div className="flex-1 pr-4 text-right pt-4">
                    <span style={{marginRight: 8}}>Seguici su:</span>
                    <LinkedInIcon style={{marginRight: 8}} />
                    <YouTubeIcon style={{marginRight: 8}} />
                    <FacebookIcon />
                </div>
                <div className='pt-4'>
                    <span>Contatti</span>
                </div>
            </div> */}

            {/*<div className="flex items-center pt-4 pr-16 bg-blue-400 shadow-xl" style={{height: '80px'}}>
                <div className="flex">
                    <span className="font-bold text-4xl pb-4" style={{flex: '1 0 0%'}}>Consulting portal</span>
                </div>
                <div className="flex flex-1 justify-center">
                    <span className='text-left font-bold text-4xl pb-4'>{title ? title : 'My portal home'}</span>
                </div>
                <span style={{marginRight: '1rem'}}>Abbonati</span>
                <PersonOutlineIcon />
                <span style={{marginLeft: '0.5rem'}}>Accedi</span>
            </div>
            */}
        </div>
    )
}

//Old
// function Header(props: HeaderProps)  {
//     return (
//         <div style={{height: '60px', textAlign: 'center'}}>
//             <Head>
//                 <title>Next SSR Application</title>
//                 <meta name="description" content="Generated by create next app" />
//                 <link rel="icon" href="../favicon.ico" />
//             </Head>           
//             <Link href="/">
//                 <a><h2>My Header</h2></a>
//             </Link>
//         </div>
//     )
//   }
  

export default Header
  